name: pre-commit

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Cache ASDF
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        id: asdf-cache
        with:
          path: ~/.asdf/
          key: ${{ runner.os }}-asdf-${{ hashFiles('.tool-versions') }}
          restore-keys: ${{ runner.os }}-asdf-

      - name: Cache pip
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.cache/pip/
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', '.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup ASDF
        uses: asdf-vm/actions/setup@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3.0.2
        if: ${{ steps.asdf-cache.outputs.cache-hit == 'true' }}

      - name: Install ASDF
        uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3.0.2
        if: ${{ steps.asdf-cache.outputs.cache-hit != 'true' }}

      - name: Reshim installed ASDF tools
        shell: bash
        run: asdf reshim

      - name: Install pip dependencies
        run: pip install -r requirements.txt

      - name: Run pre-commit
        run: pre-commit run --show-diff-on-failure --color=always --all-files
