name: pre-commit

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - uses: pre-commit/action@v3.0.1
