name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: 0 4 * * *

permissions: {}

jobs:
  renovate:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Generate GitHub App token
        id: lara-renovate-app-token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
        with:
          app-id: ${{ secrets.LARA_RENOVATE_APP_ID }}
          private-key: ${{ secrets.LARA_RENOVATE_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Renovate
        uses: renovatebot/github-action@c21017a4a2fc9f42953bcc907e375a5a544557ec # v41.0.18
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ONBOARDING: false
        with:
          token: ${{ steps.lara-renovate-app-token.outputs.token }}
