name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: 0 4 * * *

permissions: {}

jobs:
  renovate:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Generate GitHub App token
        id: lara-renovate-app-token
        uses: actions/create-github-app-token@af35edadc00be37caa72ed9f3e6d5f7801bfdf09 # v1.11.7
        with:
          app-id: ${{ secrets.LARA_RENOVATE_APP_ID }}
          private-key: ${{ secrets.LARA_RENOVATE_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Renovate
        uses: renovatebot/github-action@cf5954a2aac7999882d3de4e462499adde159d04 # v41.0.17
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ONBOARDING: false
        with:
          token: ${{ steps.lara-renovate-app-token.outputs.token }}
